### ISSUE TITLE
Allow the user to choose a seat from the whole table

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/pangea-poker#244]
The user should be able to choose any seat from a table of 9 seats, excluding taken seats.

- show occupied/free seats
- confirm seat selection with backend
- handle rejection of the chosen seat by showing notification to the user that he needs to choose again

EDIT:
- request "walletInfo" from backend
- request "backend status"

**Comment by sg777** [comment]
Hi Daria,

The backend is sending the seats info, once the DCV node clicks the start.

At the moment while entering the IP, we are clicking player1 and player2 and entering the IP, with that the seat position is getting prefixed on the GUI. I pulled the latest changes from the master, since after entering the IP I can see SIT HERE in the GUI by default at a prefixed position, what I would like to understand that by default on the GUI it should be shown SIT HERE for all the seats right?
I would like to understand at what time does the GUI is expecting to send the seats info, like after entering the IP and after click on the set nodes.
To make it generic, can we remove player1 and player2 and keep only the player table with an option to enter the IP and connect to the backend. Please let me know if I missing anything in the GUI. 

Regards,
sg777

**Comment by piggydoughnut** [comment]
@sg777

> The backend is sending the seats info, once the DCV node clicks the start.

I just checked it out, the `seats` method looks good. I just need it earlier, when people join the table.

> I pulled the latest changes from the master, since after entering the IP I can see SIT HERE in the GUI by default at a prefixed position, what I would like to understand that by default on the GUI it should be shown SIT HERE for all the seats right?

1. The latest changes are on the `dev` branch. `master` will only have releases.
2. It should only show SIT HERE on the seats which are not occupied by other players. So I need the seating information right after the player joins. Check this one: 
https://github.com/chips-blockchain/bet/issues/136

> I would like to understand at what time does the GUI is expecting to send the seats info, like after entering the IP and after click on the set nodes.

Yep. Exactly.

> To make it generic, can we remove player1 and player2 and keep only the player table with an option to enter the IP and connect to the backend. Please let me know if I missing anything in the GUI.

Yes, I did that but I didnt merge it because the game cannot function without me getting the other users seat selection after they join. You can check it out on this branch https://github.com/chips-blockchain/pangea-poker/tree/244_users_choosing_a_seat
It is work in progress since it simulates the info from the backend. There is a test data set which simulates the occupied seats information and shows the user who is already at the table

**Comment by piggydoughnut** [comment]
Done
