### ISSUE TITLE
Handle players using the same IP to connect

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/pangea-poker#275]
## In preparation for the alpha release
We will run a few player nodes for the alpha testers.
In order to make this work we need a mechanism which will check if the IP is already used in the game.

## Frontend 
The frontend should confirm the IP entered by the player with the backend before proceeding to the game, by sending a request.

## Backend
Has to respond to the request from frontend providing info on the IP.

## How to proceed
- plan the method and reponse with backend
- integrate changes in the frontend

**Comment by sg777** [comment]
The player node in the back end(BE) is binding to a specific port. Here the BE node is running the web server on port 9000, so it's not possible to start two instances of the playing node in the BE. But there is a possibility that many web clients can connect to the BE, so for that if one web client is connected to the BE I'll be blocking any further web clients connecting to the BE.

Apart from that the one approach that was discussed is to have some password based approach for the web GUI to authenticate to the BE, for this the password has to be configured or given in the BE at the time of starting the BE and also right now since the websockets are getting connected without any secure channel so for these reasons this password based approach is only be effective when we have wss sockets in place.

**Comment by piggydoughnut** [comment]
perfect! Thank you @sg777. For now we can close this as this is only the alpha version fix.
