### ISSUE TITLE
Any first bet results in FAILURE

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#34]
<a href="http://i.norbert.dev/39e793" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/1i2k0S1t2i2r3G3u0Y2O/Image%202019-10-29%20at%203.03.10%20PM.png" style="display: block;height: auto;width: 100%;"/></a>
<a href="http://i.norbert.dev/e86358" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/1r0N3C3T2P343s3k1a0D/Image%202019-10-29%20at%203.03.37%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

Any first bet pre-flop, weather it is call or raise, results in `FAILURE` on the player node that initiated the action.

Pastebin: https://pastebin.com/Qt4dq4Mv

Branches used:
- frontend: `master` at 0bb0701
- bet: `master` at sg777/bet@bcc864f

**Comment by sg777** [comment]
Thank you for finding this bug, fixed it in the above commit. I find the scenario in which this issue arises is very interesting and can happen quite often.

The root cause of this is, once the channel got established and then disconnected it shows channel state as 3, which means channel got established and with issue I realized that it doesn't mean the existing channel is active.

So for this, I checked the channel connection state from `listpeers` and if the channel is not connected active im connecting it again.
